name: run the_morning.py

on: 
  schedule:
    - cron: "30 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install playwright prereq
        run: npm install @playwright/test

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run playwright executable
        run: python -m playwright install

      - name: execute py script # run main.py
        env:
          WEBHOOKS: ${{ secrets.WEBHOOKS }}
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        run: python main.py

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
